export const defaultTimingsOfChildHabits = {
  yoga: {
    timings: '4:00 PM - 6:00 PM',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  football: {
    timings: '5:00 PM - 6:00 PM',
    days: ['Tue', 'Wed', 'Thu'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  swim: {
    timings: '5:00 PM - 6:00 PM',
    days: ['Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  art: {
    timings: '4:00 PM - 5:00 PM',
    days: ['Wed'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 1,
  },
  chess: {
    timings: '4:00 PM - 5:00 PM',
    days: ['Sat'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 1,
  },
  reading: {
    timings: '7:30 PM - 8:00 PM',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 30,
    numberOfTimesPerWeek: 5,
  },
  phonetics: {
    timings: '3:00 PM - 4:00 PM',
    days: ['Tue'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 1,
  },
  basketball: {
    timings: '4:00 PM - 6:00 PM',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  cricket: {
    timings: '4:00 PM - 6:00 PM',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  'table tennis': {
    timings: '4:00 PM - 6:00 PM',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  taekwondo: {
    timings: '4:00 PM - 6:00 PM',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  dance: {
    timings: '12:00 PM - 1:00 PM',
    days: ['Sat', 'Sun'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  skating: {
    timings: '4:00 PM - 6:00 PM',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  gymnastics: {
    timings: '4:00 PM - 6:00 PM',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  music: {
    timings: '4:00 PM - 5:00 PM',
    days: ['Mon'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 1,
  },
  squash: {
    timings: '4:00 PM - 6:00 PM',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
  karate: {
    timings: '4:00 PM - 6:00 PM',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlotInMinutes: 60,
    numberOfTimesPerWeek: 2,
  },
}
