export enum ApiErrorCode {
  'E0001' = 'Our servers are witnessing an issue. Please try again after some time',
  'E0002' = 'User not authorised',
  'E0003' = 'Request is not valid',
  'E0004' = 'Invalid Login Provider',
  'E0005' = 'Password and Confirm password are not matching',
  'E0006' = 'Email already exists',
  'E0007' = 'You cannot add more than four kids',
  'E0008' = 'You cannot add more than one partner',
  'E0009' = 'More than one user is not allowed to add',
  'E0010' = 'Relationship is invalid',
  'E0011' = "Kid's age must be minimum 3 years",
  'E0012' = 'Work and sleep hours cannot overlap.',
  'E0013' = 'Access Token is missing',
  'E0014' = "Family member doesn't exist",
  'E0015' = 'StartDate must be less than EndDate',
}
