export enum ApiErrorCode {
  'E0001' = 'Our servers are witnessing an issue. Please try again after some time',
  'E0002' = 'User not authorised',
  'E0003' = 'Request is not valid',
  'E0004' = 'Invalid Login Provider',
  'E0005' = 'Password and Confirm password are not matching',
  'E0006' = 'Email already exists',
  'E0007' = 'You cannot add more than four kids',
  'E0008' = 'You cannot add more than one partner',
  'E0009' = 'More than one user is not allowed to add',
  'E0010' = 'Relationship is invalid',
  'E0011' = "Kid's age must be minimum 3 years",
  'E0012' = 'Work and sleep hours cannot overlap.',
  'E0013' = 'Access Token is missing',
  'E0014' = "Family member doesn't exist",
  'E0015' = 'Start Date must be less than End Date',
  'E0016' = "Start Date and End Date should not be less than today's date",
  'E0017' = 'Notify Date must not be greater than start date',
  'E0018' = 'Date Of Birth is missing',
  'E0019' = 'First Name is missing',
  'E0020' = 'Last Name is missing',
  'E0021' = 'Atleast 2 habits must be added',
}
